<template>
  <div class="mx-2 mt-20">
    <Title title="Development" class="" subtitle="WEB">
      <p class="text-2xl leading-normal text-white sm:text-xl">
       Most of today’s applications run on the web. The browser has become the reference platform, a truly universal “operating system”. Modern standards allow word processors, real-time audio and video communications, and even 3D games to run in the browser. 
      </p>
    
      <p class="text-2xl leading-normal text-white sm:text-xl">
       From the traditional desktop browser to TVs and smartphones, we create web interfaces that work well and look good in any environment. We can also build the services and algorithms to manage the data generated by those web interfaces, should you require it.
      </p>
    </Title>
    <div class="mt-20 sm:mt-10 mx-16 sm:mx-8 flex flex-col items-end justify-center">
      <div class="flex flex-col items-left max-w-xl">
        <h3 class="text-gray-400 text-3xl hover:underline py-8 uppercase leading-normal font-bold">
          <nuxt-link to="/development">UI/UX</nuxt-link>
        </h3>
        <p class="text-gray-100 text-xl  leading-loose">
          We start with a prototype. A prototype is not a finished website - it is the general idea. It could be a drawing, or an actual webpage, but the important thing is to have a deep understanding of the requirements. We then start building the end product. We like using frameworks such as Vue.js and Nuxt, as they allow us to quickly get a project running, but also to split it up into smaller modules when it starts growing.
        </p>
      </div>
      <div class="flex-grow max-w-3xl" ></div>
      <div class=" flex flex-col items-left max-w-xl mt-20">
        <h3 class="text-gray-400 text-3xl hover:underline py-8 uppercase leading-normal font-bold">
          <nuxt-link to="/marketing">Web Animations</nuxt-link>
        </h3>
        <p class="text-gray-100 text-2xl sm:text-2xl leading-loose">
         Take your website to the next level. Nothing grabs your attention like animation, and we can make your sites truly stand out by including both 2D animation and 3D graphics on your webpage.
        </p>
      </div>
  
    </div>
    <Quote
      class="ml-10"
      quote="The details are not the details, they make the design."
      author="~ C. Eames"
    />
  </div>
</template>
<script>
export default {
  transition(to, from) {
    return "slide-right";
  },
  props: {
    quote: {
      type: String,
      default: "",
    },
  },
};
</script>
<style scoped>
a::after {
  content: " →";
}
</style>
